language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run lib
  - npm test
after_success:
  - npm run-script coveralls
notifications:
  email: false
